// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearJobs() {
  return window['go']['main']['App']['ClearJobs']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function SaveDownloadedFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDownloadedFile'](arg1, arg2);
}

export function ShowSaveFileDialog(arg1) {
  return window['go']['main']['App']['ShowSaveFileDialog'](arg1);
}

export function YoutubeDownload(arg1) {
  return window['go']['main']['App']['YoutubeDownload'](arg1);
}
