// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearJobs():Promise<void>;

export function GetJobs():Promise<Array<main.Job>>;

export function SaveDownloadedFile(arg1:string,arg2:string):Promise<main.DownloadResponse>;

export function YoutubeDownload(arg1:main.DownloadRequest):Promise<main.DownloadResponse>;
