// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearJobs() {
  return window['go']['main']['App']['ClearJobs']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function YoutubeDownload(arg1) {
  return window['go']['main']['App']['YoutubeDownload'](arg1);
}
